api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json:  ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]

    defaults:
        pagination_enabled: false
        pagination_items_per_page: 5
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        collection:
            pagination:
                enabled_parameter_name: pagination
                items_per_page_parameter_name: count