vich_uploader:
    db_driver: orm

    mappings:
        promo_image:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/assets/img/'
            # Will rename uploaded files using a uniqueid as a prefix.
